export const STANDARD_OPTIONS = [{ label: "API Key", value: "1" }];
export const POST_PROCESSING = [{ label: "Post Processing", value: "37" }];
export const NON_STANDARD_OPTIONS = [
  { label: "http", value: "2" },
  { label: "https", value: "3" },
  { label: "egatwsdl", value: "4" },
  { label: "imap", value: "5" },
  { label: "iwis", value: "6" },
  { label: "haiipic", value: "7" },
  { label: "haiipic2", value: "8" },
  { label: "cpy", value: "9" },
  { label: "swan", value: "10" },
  { label: "swat", value: "11" },
  { label: "webext", value: "12" },
  { label: "webextdata", value: "13" },
  { label: "wrfroms", value: "14" },
  { label: "swan_img", value: "15" },
  { label: "tmd_report", value: "16" },
  { label: "md_waterlevel", value: "17" },
  { label: "md_waterlevel_history", value: "18" },
  { label: "hd_waterlevel", value: "19" },
  { label: "moph_hospital", value: "20" },
  { label: "gen_img_hourly", value: "21" },
  { label: "tmd_rainmonth", value: "22" },
  { label: "rid_hydro", value: "23" },
  { label: "rid_hydro_oauth1", value: "24" },
  { label: "bma_basic_auth", value: "25" },
  { label: "egat_water", value: "26" },
  { label: "rid_dam_metadata_oauth1", value: "27" },
  { label: "rid_dam_data_oauth1", value: "28" },
  { label: "jtwccurrent", value: "29" },
  { label: "rid_reservoir", value: "30" },
  { label: "rid_reservoir_dam", value: "31" },
  { label: "disaster", value: "32" },
  { label: "ftp_hii", value: "33" },
  { label: "rid_wl_googlesheet", value: "34" },
  { label: "ftp", value: "35" },
  { label: "sftp", value: "36" },
];
